apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-orquestrar
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/fch-bsp/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./sync-hooks-waves/06-waves-and-hooks # monitorando de 3 em 3 minutos 
  destination: 
    server: https://kubernetes.default.svc
    namespace: example06

  # syncPolicy:
  #   syncOptions:
  #   - CreateNamespace=true

    # automated:
    #   selfHeal: false
    #   prune: false