---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
  namespace: example06
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - name: webserver-simple
        image: docker.io/kostiscodefresh/gitops-simple-app:v2.0
        ports:
        - containerPort: 8080

# 1 db-upgrade.yml -> PreSync, wave 10
# 2 cleanup.yml -> PostSync, wave 20
# 2 disable-alerts.yml -> PreSync, wave 20
# 3 enable-alerts.yml -> PostSync, wave 30
# 3 slack-notify.yml -> PostSync, wave 30
# 4 deployment
# 5 servicegrafana-notify.yml -> Sync, wave -10
# 6 smoke-test.yml -> PostSync, wave 10