apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-staging
  namespace: staging
spec:
  project: default

  source:
    repoURL: https://github.com/fch-bsp/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./environment-promotion/envs/staging # monitorando de 3 em 3 minutos 
  destination: 
    server: https://kubernetes.default.svc
    namespace: goapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    # automated:
    #   selfHeal: false
    #   prune: false