apiVersion: batch/v1
kind: Job
metadata:
  namespace: example05
  name: cleanup-after-sync
  annotations:
    argocd.argoproj.io/sync-wave: "10" 
spec:
  template:
    spec:
      containers:
      - name: dummy-run
        image: alpine
        command:
          - "sleep"
          - "10"
      restartPolicy: Never
  backoffLimit: 2    

# 0 artifact -> namespace
# 1 artifact -> db-update -20
# 2 artifact -> grafana-notify -10
# 3 artifact -> deplotment default
# 5 artifact -> service default
# 6 artifact -> cleanup 10