apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: example05
spec:
  type: ClusterIP
  selector:
    app: trivial-go-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

# 0 artifact -> namespace 
# 1 artifact -> db-update -20
# 2 artifact -> grafana-notify -10
# 3 artifact -> deplotment default
# 5 artifact -> service default
# 6 artifact -> cleanup 10